map('n', '<Leader>gs', '<cmd>lua require"config.utils".git_status()<CR>', opts)
map('n', '<A-Up>',     '[c', opts)
map('n', '<A-Down>',   ']c', opts)
map('n', '<A-Right>',  ':diffget //2<CR>', opts)
map('n', '<A-Left>',   ':diffget //3<CR>', opts)
